"use client";
import { FormEvent, useState } from "react";
import { AdminPageHeader, NotImplemented } from "@/components/payment-page-admin";

export default function LaunchPaymentPage() {
  const [result, setResult] = useState<Record<string, string> | null>(null); const [message, setMessage] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const tenantKey = String(form.get("api_key") ?? "").trim(); const payload = { invoice_id: String(form.get("invoice_id") ?? "").trim(), theme_id: String(form.get("theme_id") ?? "").trim(), success_url: String(form.get("success_url") ?? "").trim(), cancel_url: String(form.get("cancel_url") ?? "").trim() }; if (!tenantKey) { setMessage("API key tenant diperlukan untuk membuat PaymentSession."); return; } const response = await fetch("http://127.0.0.1:8080/v1/payment-sessions", { method: "POST", headers: { "Content-Type": "application/json", "X-API-Key": tenantKey, "Idempotency-Key": String(form.get("order_id") ?? crypto.randomUUID()) }, body: JSON.stringify(payload) }); if (!response.ok) { setMessage(`Create PaymentSession gagal (${response.status}). Pastikan invoice dan redirect URL sudah terdaftar.`); return; } const data = await response.json(); setResult(data); setMessage("Payment page berhasil dibuat dari PaymentSession backend."); }
  return <div className="page"><AdminPageHeader title="Launch Payment" description="Buat hosted payment page langsung melalui PaymentSession existing." /><form className="form-module launch-form" onSubmit={submit}><div className="form-grid"><label>Amount<input name="amount" inputMode="numeric" placeholder="100000" required /></label><label>Description<input name="description" placeholder="Order description" /></label><label>Merchant Order ID<input name="order_id" placeholder="order-123" required /></label><label>Expiration<input name="expiration" type="datetime-local" /></label><label>Theme ID<input name="theme_id" placeholder="theme_opaque_id" required /></label><label>Tenant API Key<input name="api_key" type="password" placeholder="X-API-Key" required /></label><label>Success URL<input name="success_url" type="url" placeholder="https://merchant.example/success" required /></label><label>Cancel URL<input name="cancel_url" type="url" placeholder="https://merchant.example/cancelled" required /></label><label>Failed URL<input name="failed_url" type="url" placeholder="https://merchant.example/failed" /></label><label>Expired URL<input name="expired_url" type="url" placeholder="https://merchant.example/expired" /></label></div><button className="button button-primary" type="submit">Create Payment Page</button>{message && <p className="theme-message" aria-live="polite">{message}</p>}</form>{result && <section className="result-module"><h2>Payment Session created</h2>{Object.entries(result).map(([key, value]) => <div key={key}><span>{key}</span><code>{String(value)}</code></div>)}{result.checkout_url && <div className="page-actions"><a className="button button-primary" href={result.checkout_url} target="_blank" rel="noreferrer">Open Payment Page</a><button className="button" onClick={() => void navigator.clipboard.writeText(result.checkout_url ?? "")}>Copy Payment URL</button></div>}</section>}<NotImplemented>Amount, description, dan redirect metadata mengikuti invoice yang sudah ada di backend; endpoint create PaymentSession tidak membuat invoice baru.</NotImplemented></div>;
}
