[program:cdp-proxy]
command=/usr/bin/python3 /opt/xloyal/cdp-proxy.py
autorestart=true
priority=850
user=root
stdout_logfile=/var/log/neko/cdp-proxy.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=2
redirect_stderr=true
