[program:cdp-proxy]
command=/usr/bin/socat TCP-LISTEN:9222,bind=0.0.0.0,reuseaddr,fork TCP:127.0.0.1:9223
autorestart=true
priority=850
user=root
stdout_logfile=/var/log/neko/cdp-proxy.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=2
redirect_stderr=true
