[program:neko-helper]
command=/usr/bin/python3 /opt/xloyal/neko-helper.py
environment=DISPLAY=":99.0"
autorestart=true
priority=850
user=root
stdout_logfile=/var/log/neko/neko-helper.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
redirect_stderr=true
